services:
  server:
    image: sticky_sessions_server
    build:
      context: ../code/server
    ports:
      - "8080-8081:8080"
    networks:
      - sticky_sessions_net

  nginx:
    image: nginx:alpine
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:80"
    networks:
      - sticky_sessions_net

networks:
  sticky_sessions_net:
    driver: bridge
